function quest3 () {
    pauseUntil(() => controller.anyButton.isPressed())
    if (controller.A.isPressed()) {
        adventure.changeScoreOverride(adventure.Currency.Coins, -3)
        adventure.clearTextLog()
        adventure.addToTextlog("Great choice! You begin to travel through the swamp on your trusty companion.")
        quest4()
    } else {
        adventure.changeScoreOverride(adventure.Currency.Coins, -2)
        adventure.clearTextLog()
        adventure.addToTextlog("Too bad. Your guide gets sick before he takes you to the swamp, dropping out at the last second and taking your gold with him.")
        info.changeLifeBy(-1)
        quest2()
    }
}
function quest4 () {
	
}
function quest1 () {
    music.play(music.createSong(assets.song`a_fairy_and_an_ogre`), music.PlaybackMode.InBackground)
    adventure.addImageToTextLog(img`
        ..............................fffffeeee.........................
        ............................ffffffffffefc.......................
        ............................f888888fffeee.......................
        ...........................f8f88888fffeee.......................
        ..........................fff888ffffff..........................
        .........................ff8888ffffffff.........................
        .........................fff88fffccffff.........................
        .........................ffffffc4ddffff.........................
        .fff.....................fffff444444fff.........................
        .fbcf....................ffffffd4ffdfff.........................
        .fbbcf...................ffffdddddddffff........................
        .fcbcff..................ffffdddddddffff........................
        ..fbbcf................ccffffddddddfffffccccc...................
        ..ffbbcf.............cc1bffffd22dddffffffbbbbc..................
        ...ffbcff............c1bff88ffddddffffcfbbb1bbc.................
        ....ffbcf............cbbff88ffffeeeffcbbbbbb1bc.................
        .....fbbcf...........cbbff88ffffeeefcbbbbbbb1bc.................
        .....ffbccf..........ccbcf88ffffdddfccbbbbbbbbc.................
        ......fbbcff........ccccff88ff6fcccc66cbbbbbb9c.................
        .......fbbcff.......cc96ff88ff66666c666ccccc96c.................
        .......ffbbcf.......c996ff88ff66666c6666666c6c..................
        ........fbbcff.......c66ff88ff66666fc666666fcc..................
        .........fbbcf.......cf6ffffff6666ffcc6666ccc...................
        .........ffbccf.......c6ffffff6666fdfcc666cc....................
        ..........ffbcff......fcffffffcc6ffddbfc6cc8....................
        ...........fbbcff......fefffffc66fddddffcccff...................
        ............fbccf....d.fefffffe6fddddeffcccff...................
        ............ffbccf.....ffefffffffdddeef66cfff...................
        .............fbbcff.....ffefffffddddeff66cf8f...................
        ..............fbccff....fdeffffffddeff66ccfff...................
        ..............ffbccf...fdeefcffdddeff66ccffff...................
        ...............fbbcff.ffeeefffdddeff66c66c......................
        ................fbbbf8feeeffdddeeffffffffc......................
        ...............debbbffffffdddeedfffefeeeefc.....................
        .................f8ffffdddeeeffffccfffffffc.....................
        .................ffffdddeefffefff1ffffccc6fc....................
        ................ffffdddeffcccfaae88eaafccce6c...................
        ...............fff.fedefffcccfaae88eaafcccefcc..................
        ...................feefffccccfaae88eaafccceffc..................
        ....................ff.fcccccfaae88eaafccccefc..................
        ......................fffccccfaae88eaafcccceff..................
        ......................fffcccefaae88eaafccccecf..................
        .....................ffcccccefaae88eaafccccccff.................
        ....................ffccccccefaae88eaafeccccccf.................
        ....................ffccccceefaaaeeaaafeecccccff................
        ...................ff2ccceeeffffaaaaffffeeeec22f................
        ...................ff22cceeef.cfaaaaff.ffeee222f................
        ...................f2222ceef....faaf....cee2222f................
        ...................fffffffe.....ffff.....cfffffff...............
        ....................fffffff..............ffffffff...............
        ....................fffffff..............ffffffff...............
        .....................ceeeef...............feeeec................
        ....................cfeeeef...............feeeecc...............
        ....................cfeeeeff.............ffeeeecc...............
        ....................ccceeeff.............ffeeeccc...............
        .....................fceeeff.............fffeecf................
        .....................feeef.................feeef................
        .....................feeef.................fdeef................
        ....................fdeeef.................ffedef...............
        ..................ffeeedef..................feeeff..............
        .................ffeeeeeff..................feeeeef.............
        ..................ffffffff..................cffffff.............
        ................................................................
        ................................................................
        `)
    adventure.addToTextlog("A wandering andventurer approaches and asks you to join her quest to slay a dragon.")
    adventure.addToTextlog("Press (A) to help her.")
    adventure.addToTextlog("Press (B) to be a loser.")
    pauseUntil(() => controller.anyButton.isPressed())
    if (controller.A.isPressed()) {
        adventure.clearTextLog()
        adventure.addToTextlog("Great choice! The wandering adventurer pays you five gold to join her.")
        adventure.changeScoreOverride(adventure.Currency.Coins, 5)
        quest2()
    } else {
        adventure.clearTextLog()
        adventure.addImageToTextLog(img`
            ..............................................................................1
            11.ccc.......................................................................1.
            ..1111ccc...................................................................1c.
            ...cc5111ccccc............................................................11cc.
            .....c5551111ccc.........................................................1bcc..
            ......ccc5555111cccccc..................................................1ccbc..
            .........1ccc555111111cccc............................................11cbcc...
            ..........1ccccc5555551111ccc........................................1bcbcc....
            ...........1cccccccccc5555111ccc....................................1ccbccc....
            ............1ccccccccccccc555111cc.................................1c55cccc....
            ............1cccccccccccccccc55511c...............................1c55cccc.....
            ...........1cccccccccccccccccccc551c.............................1555cccbc.....
            ...........1cccccccccccccbcbcbbc5551c...........................1555cccbcc.....
            ...........1cccccccccbcbcbbbb55555511c.........................1555c5ccccc.....
            ..........1cccccccbcbcbcbbb55cc55ccc11c.......................1555ccc55ccc.....
            .........1.ccbcbcbcbcbbbbb5ccc551...c11c.....................1c155ccccc55c.....
            ........1.ccbcbcbcbbbbbbb5ccc5c51....cc......................1c1ccccbcccccc....
            .....111.bbbbbbbbbbbbb555ccc5cc51............................1c1cccbcc.........
            ......ccbbbbbbbbbbb555ccccc5ccc51............................1c1ccbcc..........
            .......c55555555555ccccccc5ccccc51.......111111..............1c1cccb...........
            .........cccccccccccccccc5ccccccc51...c1155555511............1cccccc...........
            ..........ccccccccccccccb5ccccccc551.cbbbbbbbcc551...........1cc5ccc...........
            ...........ccccccccccccb5cccccccc5c515bbbbbbbbbc551..........1ccc5cc...........
            ............ccccccccccbc5cccccbcc5cc515bbbbbbbbbc551........1ccccc5cc..........
            ............cccccccbcbcb5ccccbccc5ccc515bbbbbbbbbc551.......1cccccc............
            ...........1..ccccbcbcb5ccccccbcc5cccc515bbbbbbbbbc551b.....1cccbc.............
            .........115c..ccccbcbb5cccbcbccc5ccccc515bbbbbbbbbc551b....1ccbc..............
            ........1b5bc..cccbbbb5cccccbcbcc5cbcccc515bbbb1bbbbc51bb..1ccccc..............
            .......1b5bc...ccbcbbb5ccccccbcc5cccbcccc515bbbb1bbbbc51bb..cccbc..............
            ......1b5bbc...cccbbb5ccccbcbccc5ccbcccccc515bbbb1bbbc51bbbcccbcc..............
            .....1b15bc....cccbb5ccccbcbcccc5cccccccccc515bb1b1bbbc51bbccccbc..............
            ...c1b15bbc....ccbb5ccccccccbcc5ccccbbbbcccc51bbb1bbbbc51bbbccccc..............
            ..c1b1b5bc.....cbb5cccccccccccccccbbbbbbbcccc15bbb1bbbbc51bbccccc..............
            ..c1bbb5bc.....cb5.......cccccccbbbbbbbbbbbcb15bbbbbbbbc51bbbccc...............
            ..c1bbbb5c......5........1cccccbbbbbbbbbbbbbb15bbbbbbbbbc51bbbcc...............
            ..c1cbbb51c....c........1cbbcbbbbbbbbbbbbbbbbb15bbbbb1bbc51bbb5c...............
            ..1bcbbbb51c...........1ccbbbbbbbbbbbbbbbbbbbb15bbbb1bbbb51bbbb1...............
            ..11ccbbbb511.........1cc1bbbbbbbbbbbbb1b1bbbb155bbbb1bbb51bcbb1...............
            ...1cccbb1b51cc...1111cc1bbbbbbbbbbbbb1b1b1bbbb15bbb1bbbb51bbbb1...............
            ...1ccccbb1b511111555b11bbbbbbbbbbbbbbb1b1bbbbb15bb1b1bbb51bcbb1...............
            .....ccccbbbb55555bbb11bbbbbbbbbbbbbbbbbbb1bbbb15bbbbbbbb51bbbb5...............
            ......ccccbbbbbbbbbbb1bbbbbbbb1bbbbbbbbbbbbbbbb15cbbbbbbc51bbcb5...............
            .......ccccbcbbbbbbb1b1bbbbbb1b1bbbbbbbbbbbbbbb15cbcbcbb15cbcbb5...............
            ........ccccbcbcbcbc11bbbbbb1b1b1bbbbbcbbbbcbbb15cbbcbbb15cbbcb5...............
            ..........cccccbcbcc1b1bbbbbb111b1bbbcbbcbcbbbb15cbcbcbb15cbcbb5...............
            ...........ccccccccc11bbbbbb1b1111cbbbbbbcbbbbb15cbbcbb15cbbbb15...............
            ..............ccccccc1bbbbbbb11111cbbbbbcbbbbbb15cbcbbb15cbbbb15...............
            ...............cccccc1bbbbbbbb11111cbbbbbbbbbcb15cbbbb15cbcbb15................
            ..................cccc1ccbbcb1b1111cbbbbbbbbcbc15cbcbb15cbcbb15................
            .......................1bbbbbb11111cbbbbbbbcbcc15cbbb15cbbbb15.................
            ........................cbbcbcb1111cbbbb1bbbcbc1cbbb15c1bbbb15.................
            .........................cbbcbcb1111cbbb11bbbb11cbbc1515cbb15b.................
            ..........................cbbcbbb111.cbb151bbb15cbc1515ccb115..................
            .........................cccbbbbcb1b.cbc1c51b15b1b1515cbcb15b..................
            .........................ccccbbcbcbbc.bc1bc51cc51cc15cbbc15bc..................
            ........................ccccccbbcbcbc.cb1bbc51cccc15cbbbc5bcc..................
            ........................cbcccccbbbbc..bb1bbbc5bbbb5cbbbbcbcccb.................
            ........................ccbcccccccc...cb1bbcbcbbbcbccbbbccccbcb................
            ........................cbcccc.........1cbbcbbcccbbccbbbcccccbcb...............
            ........................1cbccc.........1bcbbccbcbcccbbcbbc.cbcbb...............
            ........................1bcbcc.........1b4cbcbcccbccbc4bbc..bbbbbb.............
            .........................1bcbcc........1b45cbcbcbccbc54bbc...bbbbbb.1.b........
            ..........................cbbbc........1bbf4cbccccbc4fbbbc....bbbbbb.b.b.......
            ..........................c1bbbc.......1bbbbbbbbbbbbbbbbbc.....bbbbbb.11b......
            ...........................c1bbbc......1ccbbcccbcccbbccb1c....bb111bb1111b.....
            ............................c1bbbc.....cc1ccbbbcbbbcc11cb........11............
            ............................cb1bb11....c211cbcbcbcbc11c2c.........1............
            ............................c1b1cb11...cb1c1cbbcbbc1c1cc..........1............
            ...........................c1bc.1ccc1...cbcc1ccccc1cc2c........................
            ...........................c1c...1.cc....cbcc11b11cc2bc........................
            ............................c.............cb21ccc1c2bc.........................
            ...........................................cb21c122bc..........................
            ...........................................ccbb2bbbc...........................
            ...........................................cccb2bcccb..........................
            ...........................................bccbbbc.............................
            ...........................................cbccccc.............................
            ...........................................bcbcbcc.............................
            ............................................bcbcbc.............................
            ..........................................cbcbbbbb.............................
            ..........................................bcbbbbbb.............................
            ..........................................cbbbbbbb.............................
            ..........................................cccbbbb..11..........................
            ..........................................bccccbb111.1.........................
            ..........................................1b1b111...1..........................
            ...........................................11.11.11............................
            ...........................................11..1..1............................
            ...........................................11..1...1...........................
            ...........................................1...1...............................
            `)
        adventure.addToTextlog("You are a big loser. The dragon swoops from the sky and flays you alive.")
        info.changeLifeBy(-3)
    }
}
function quest2 () {
    adventure.clearTextLog()
    adventure.addToTextlog("You must pass through a swamp full of ghosts to continue towards the lair of the dragon.")
    adventure.addToTextlog("Press (A) to chose a horse as a mount to traverse the swamp for a price of three gold.")
    adventure.addToTextlog("Press (B) to chose a guide to take you through the swamp for a price of two gold.")
    quest3()
}
info.onLifeZero(function () {
    game.gameOver(false)
})
adventure.setScoreOverride(adventure.Currency.Coins, 0)
info.setLife(3)
quest1()
